#include "equivalence/sqlite_column_rules.hpp"

#include "equivalence/derived_digest_registry.hpp"
#include "equivalence/equivalence_profile.hpp"
#include "equivalence/json_field_rules.hpp"

#include <array>

namespace svp::validation::equivalence {
namespace {

using Profile = DefaultEquivalenceProfileV1;

struct NamedColumnRule {
  std::string_view table;
  std::string_view column;
  SqliteColumnRule rule;
};

// Columns whose class is not implied by their name.
constexpr std::array kNamedColumnRules{
    // Mirrors colors/color_observations.jsonl bucket_coverage values.
    NamedColumnRule{.table = "color_bucket_coverage",
                    .column = "coverage",
                    .rule = {.column_class = SqliteColumnClass::numeric_tolerance,
                             .rule_id = "color_bucket_coverage",
                             .tolerance = Profile::kColorBucketCoverageAbsMax}},
    // Section 17.5 "Numerical SQLite values".
    NamedColumnRule{.table = "vector_index",
                    .column = "embedding",
                    .rule = {.column_class = SqliteColumnClass::embedding_vector,
                             .rule_id = "embeddings",
                             .tolerance = Profile::kEmbeddingCosineMin}},
};

}  // namespace

SqliteColumnRule sqlite_column_rule(std::string_view table, std::string_view column) {
  for (const auto& named : kNamedColumnRules) {
    if (named.table == table && named.column == column) {
      return named.rule;
    }
  }
  for (const auto& digest : sqlite_derived_digest_columns()) {
    if (digest.table == table && digest.column == column) {
      return {.column_class = SqliteColumnClass::derived_block_digest,
              .rule_id = "derived_digest"};
    }
  }
  // "REAL confidence columns generated by floating-point processors" share
  // the JSON confidence-field naming rule.
  if (const auto* json_rule = find_json_field_rule({}, column);
      json_rule != nullptr && json_rule->rule_id == "confidence_fields") {
    return {.column_class = SqliteColumnClass::numeric_tolerance,
            .rule_id = json_rule->rule_id,
            .tolerance = json_rule->tolerance};
  }
  return {};
}

}  // namespace svp::validation::equivalence
