set(SVP_PROJECT_VERSION "1.0.0")
set(SVP_RELEASE_STAGE "RC2")
string(REGEX MATCH "^([0-9]+)\\.([0-9]+)"
  SVP_SPEC_VERSION_MATCH "${SVP_PROJECT_VERSION}")
if(NOT SVP_SPEC_VERSION_MATCH)
  message(FATAL_ERROR "SVP_PROJECT_VERSION must begin with major.minor")
endif()
set(SVP_SPEC_VERSION "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}")
string(TOLOWER "${SVP_RELEASE_STAGE}" SVP_RELEASE_STAGE_LOWER)
set(SVP_VERSION_STRING "${SVP_PROJECT_VERSION}-${SVP_RELEASE_STAGE_LOWER}")

file(READ "${CMAKE_CURRENT_LIST_DIR}/../vcpkg.json" SVP_VCPKG_MANIFEST)
string(JSON SVP_VCPKG_VERSION GET "${SVP_VCPKG_MANIFEST}" version-string)
if(NOT SVP_VCPKG_VERSION STREQUAL SVP_VERSION_STRING)
  message(FATAL_ERROR
    "vcpkg.json version-string '${SVP_VCPKG_VERSION}' must match '${SVP_VERSION_STRING}'")
endif()

file(READ
  "${CMAKE_CURRENT_LIST_DIR}/../packages/svp-core/include/svp/core/version.hpp"
  SVP_VERSION_HEADER
)
foreach(SVP_REQUIRED_HEADER_VALUE
    "kSpecVersion = \"${SVP_SPEC_VERSION}\""
    "kSpecReleaseStage = \"${SVP_RELEASE_STAGE}\""
    "kToolVersion = \"${SVP_VERSION_STRING}\"")
  string(FIND "${SVP_VERSION_HEADER}" "${SVP_REQUIRED_HEADER_VALUE}" SVP_VALUE_POSITION)
  if(SVP_VALUE_POSITION EQUAL -1)
    message(FATAL_ERROR
      "version.hpp must contain '${SVP_REQUIRED_HEADER_VALUE}'")
  endif()
endforeach()

file(READ "${CMAKE_CURRENT_LIST_DIR}/../README.md" SVP_README)
set(SVP_README_VERSION_LABEL
  "SVP v${SVP_PROJECT_VERSION} ${SVP_RELEASE_STAGE} (`${SVP_VERSION_STRING}`)")
string(FIND "${SVP_README}" "${SVP_README_VERSION_LABEL}" SVP_README_VERSION_POSITION)
if(SVP_README_VERSION_POSITION EQUAL -1)
  message(FATAL_ERROR
    "README.md must identify the release as '${SVP_README_VERSION_LABEL}'")
endif()
